language: python

python:
  - '2.7'
  - '3.4'
  - '3.5'

before_install:
 # From http://conda.pydata.org/docs/travis.html
 - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
 - bash miniconda.sh -b -p $HOME/miniconda
 - export PATH="$HOME/miniconda/bin:$PATH"
 - hash -r
 - conda config --set always_yes yes --set changeps1 no
 - conda update -q conda
 - conda info -a
 - travis_retry conda create -n test python=$TRAVIS_PYTHON_VERSION pip pytest numpy future bcolz h5py pandas toolz
 - source activate test
 - travis_retry pip install arpeggio pytest-cov pytest-pep8 codecov scrutinizer-ocular
 - travis_retry pip install blosc bloscpack joblib psutil bitshuffle
 - travis_retry pip install whatami

script:
  py.test -v -rs --doctest-modules --pep8 --cov jagged --cov-report term-missing jagged

after_success:
 - codecov
 - ocular --data-file ".coverage" --config-file ".coveragerc"

notifications:
  email: false
