language: python

python:
  - '2.7'
  - '3.4'

before_install:
 - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
 - chmod +x miniconda.sh
 - ./miniconda.sh -b
 - export PATH=/home/travis/miniconda/bin:$PATH
 - conda config --set always_yes yes
 - conda update conda
 - conda info -a
 - travis_retry conda create -n test python=$TRAVIS_PYTHON_VERSION pip pytest numpy future bcolz h5py pandas toolz
 - source activate test
 - travis_retry pip install arpeggio whatami pytest-cov pytest-pep8 codecov scrutinizer-ocular

script:
  py.test -v -rs --doctest-modules --pep8 --cov jagged --cov-report term-missing jagged

after_success:
 - codecov
 - ocular --data-file ".coverage" --config-file ".coveragerc"

notifications:
  email: false
